### ISSUE TITLE
npm WARN deprecated

### ISSUE THREAD

**Issue by brunoimbrizi** [mattdesl/canvas-sketch-cli#19]
`canvas-sketch-cli` is used in the course [Creative Coding: Making Visuals with JavaScript](https://www.domestika.org/en/courses/2729-creative-coding-making-visuals-with-javascript/bruno_imbrizi) 

The course is targeted at beginners who might not be used to NPM or the terminal in general. Many are confused by the NPM warning messages after the installation. i.e.

![AM-original](https://user-images.githubusercontent.com/880280/146602219-2b07df61-7f4a-438d-9c7f-cabaa6f09233.png)
Screenshot by [chipriggs](https://www.domestika.org/en/chipriggs)

I lost count of how many times I wrote that was nothing to worry about and canvas-sketch should still be working fine.
Today I took the time to investigate the issue and targeted not only the warning messages, but also vulnerabilities. 
The issues are coming from:

- budo > chokidar@2
- budo > watchify-middleware > watchify@3

I'm aware that updating dependencies is a low effort contribution, I'm only trying to help avoid all the confusion for the new students. 

The plan is to send two PRs: one to [budo](https://github.com/mattdesl/budo) and one to [watchify-middleware](https://github.com/mattdesl/watchify-middleware). I'll be referencing this issue on both.

**Comment by mattdesl** [comment]
I've patched this, let me know if latest versions help reduce warning spam.

Ideally a future version of canvas-sketch will not rely on budo at all, maybe using esbuild or vite for example.
